version: '3.8'

services:
  kong:
    image: kong:3.9.0
    container_name: kong-dbless
    environment:
      - KONG_DATABASE=off  
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml 
      - KONG_PROXY_ACCESS_LOG=/dev/stdout  
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout  
      - KONG_PROXY_ERROR_LOG=/dev/stderr  
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl  
      - KONG_ADMIN_GUI_URL=http://localhost:8002  
    networks:
      - kong-net
    ports:
      - "8000:8000"  
      - "8443:8443" 
      - "127.0.0.1:8001:8001"  
      - "127.0.0.1:8444:8444" 
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro  
    depends_on:
      - nestcontainer
      - expresscontainer

  nestcontainer:
    build:
      context: ./nestPlayground
    container_name: nestcontainer
    networks:
      - kong-net
    expose:
      - "3000"  
    environment:
      - NODE_ENV=production

  expresscontainer:
    build:
      context: ./expressPlayground  
    container_name: expresscontainer
    networks:
      - kong-net
    expose:
      - "3001"  
    environment:
      - NODE_ENV=production
    env_file:
      - ./expressPlayground/.env
    ports:
      - "3001:3001"  

networks:
  kong-net:
    driver: bridge
