name: Deploy to GCE

on:
  push:
    branches:
      - feature/githubActionsDev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCE_EXTERNAL_IP }} >> ~/.ssh/known_hosts

      - name: Transfer Files to VM
        run: |
          scp -i ~/.ssh/id_rsa -r ./* belforportfolioutility@${{ secrets.GCE_EXTERNAL_IP }}:/home/belforportfolioutility/dev

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa belforportfolioutility@${{ secrets.GCE_EXTERNAL_IP }} << 'EOF'
            cd /home/belforportfolioutility/dev
            docker compose down
            docker compose up -d --build
          EOF
